name: Changed files
on:
  - pull_request_target
jobs:
  changed_files:
    name: Do stuff with changed files
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read

    steps:
    - id: checkout_base
      uses: actions/checkout@v4
      with:
        ref: ${{ github.base_ref }}

    - name: Get changed Helm files
      id: changed_files_helm
      uses: tj-actions/changed-files@v44
      with:
        files: |
          infrastructure/base/*/helm.yaml

    - id: show_changed
      name: Show changed files
      env:
        CHANGED_FILES: ${{ steps.changed_files_helm.outputs.all_changed_files }}
      run: |
        echo Using env variable
        echo "Count: ${#CHANGED_FILES[@]}"

        echo "Plain: ${CHANGED_FILES}"
        echo "Count: ${#CHANGED_FILES}"
        for file in ${CHANGED_FILES}; do
            echo "$file changed"
        done
        echo

        echo "At: ${CHANGED_FILES[@]}"
        echo "Count: ${#CHANGED_FILES[@]}"
        for file in ${CHANGED_FILES[@]}; do
            echo "$file changed"
        done
        echo

        echo "Asterisk: ${CHANGED_FILES[*]}"
        echo "Count: ${#CHANGED_FILES[*]}"
        for file in ${CHANGED_FILES[*]}; do
            echo "$file changed"
        done
        echo

        echo Using output directly
        # echo "Count: ${#CHANGED_FILES[@]}"
        echo "Plain: ${{ steps.changed_files_helm.outputs.all_changed_files }}"
        for file in ${{ steps.changed_files_helm.outputs.all_changed_files }}; do
            echo "$file changed"
        done

        # echo "At: ${CHANGED_FILES[@]}"
        # echo "Asterisk: ${CHANGED_FILES[*]}"

    - id: test
      name: Test
      run: |
        helm_files=($(find ./infrastructure/base -type f -name 'helm.yaml' | sed "s|^./infrastructure/base/||"))
        files_string="${helm_files[@]}"

        echo "Plain: ${files_string}"
        echo "Count: ${#files_string}"
        for file in ${files_string}; do
            echo "$file changed"
        done
        echo

        echo "At: ${files_string[@]}"
        echo "Count: ${#files_string[@]}"
        for file in ${files_string[@]}; do
            echo "$file changed"
        done
        echo

        echo "Asterisk: ${files_string[*]}"
        echo "Count: ${#files_string[*]}"
        for file in ${files_string[*]}; do
            echo "$file changed"
        done
        echo
