name: "Conditions: List"
on:
  workflow_dispatch: {}

env:
  ADD_REVIEW_TEAM: "infrastructure"

jobs:
  main_job:
    name: "Main"
    runs-on: ubuntu-latest
    steps:
    - id: get
      run: |
        REVIEW_TEAM_SLUGS="[\"recoord/infrastructure-contributors\",\"recoord/infrastructure-maintenance\"]"
        echo "Teams assigned as reviewers: ${REVIEW_TEAM_SLUGS}"
        echo "review_team_slugs=${REVIEW_TEAM_SLUGS}" >> "$GITHUB_OUTPUT"

    - id: remove
      name: Remove review teams
      run: |
        jq -r '.[]' <<< '${{ steps.get.outputs.review_team_slugs }}' | \
        while read -r slug; do
            if [[ "${slug}" == "recoord/${ADD_REVIEW_TEAM}" ]]; then
                echo "Leaving \"$slug\" as reviewer"
            else
                echo "Removing team \"$slug\" as reviewer"
            fi
        done

    - id: add
      name: Add review team
      if: ${{ ! contains(fromJSON(steps.get.outputs.review_team_slugs), format('recoord/{0}', vars.ADD_REVIEW_TEAM)) }}
      run: |
        echo "Adding team reviewer \"$ADD_REVIEW_TEAM\""

#   contains(fromJSON('["pull_request_target"]'), github.event_name)