name: "Conditions: List"
on:
  workflow_dispatch: {}

env:
  ADD_REVIEW_TEAM: "infrastructure"

jobs:
  main_job:
    name: "Main"
    runs-on: ubuntu-latest
    steps:
    - id: get
      run: |
        REVIEW_TEAM_SLUGS="[\"recoord/infrastructure-contributors\",\"recoord/infrastructure-maintenance\"]"
        echo "Teams assigned as reviewers: ${REVIEW_TEAM_SLUGS}"
        echo "review_team_slugs=${REVIEW_TEAM_SLUGS}" >> "$GITHUB_OUTPUT"

    - id: remove
      name: Remove review teams
      run: |
        echo "${{ steps.get.outputs.review_team_slugs }}" | jq -r '.[]' | while read -r slug; do
            echo "Running command for $slug"
        done

# for t in "${review_team_slugs[@]}"; do
#     if [[ "${t}" == "${ADD_REVIEW_TEAM}" ]]; then
#         echo "Leaving \"$t\" as reviewer"
#     else
#         echo "Removing team \"$t\" as reviewer"
#     fi
# done


#   contains(fromJSON('["pull_request_target"]'), github.event_name)