name: Replace assignee
on:
  - pull_request
jobs:

  replace-assignee:
    runs-on: ubuntu-latest
    steps:

      - id: init
      name: Init
      run: |
        echo "Will replace assignee \"${{ vars.REPLACE_ASSIGNEE }}\" with \"${{ vars.REPLACE_ASSIGNEE_WITH }}\""
        echo "PR opened by \"${{ github.event.pull_request.user.login }}\""

        - id: replace-assignee
      name: Replace assignee
      if: ${{ github.event.pull_request.user.login == vars.REPLACE_ASSIGNEE }}
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh pr edit ${{ github.event.pull_request.number }} --remove-assignee "${{ vars.REPLACE_ASSIGNEE }}"
        gh pr edit ${{ github.event.pull_request.number }} --add-assignee "${{ vars.REPLACE_ASSIGNEE_WITH }}"
