name: Replace reviewer teams
on:
  - pull_request

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }} # must use PAT with "repo" scope
  PR_NUMBER: ${{ github.event.pull_request.number }}
  ADD_REVIEW_TEAM: ${{ vars.ADD_REVIEW_TEAM }}

permissions:
  pull-requests: write

jobs:
  replace-reviewer-teams:
    name: Replace reviewer teams
    runs-on: ubuntu-latest
    # Only replace reviewer team if PR was *not* opened by specific user, e.g. GitHub service account used by Renovate
    if: github.event.pull_request.user.login != vars.REPLACE_REVIEWER_TEAMS_IGNORE_PR_CREATOR

    steps:
    - id: get
      name: Get review teams
      run: |
        review_team_slugs=()
        review_teams=()
        while IFS='' read -r line; do review_team_slugs+=("$line"); done < <(gh pr view "$PR_NUMBER" --repo "$GITHUB_REPOSITORY" --json reviewRequests --jq '.reviewRequests[] | select(.__typename == "Team") | .slug')
        for t in "${review_team_slugs[@]}"; do
          tname=$(echo "$t" | cut -d'/' -f2-)
          review_teams+=("${tname}")
        done
        REVIEW_TEAM_NAMES=$(IFS=,; echo "${review_teams[*]}")
        echo "Teams assigned as reviewers: ${REVIEW_TEAM_NAMES}"
        echo "review_team_names=${REVIEW_TEAM_NAMES}" >> "$GITHUB_OUTPUT"

    - id: remove
      name: Remove review teams
      run: |
        IFS=, read -r -a review_teams <<< "${{ steps.get.outputs.review_team_names }}"
        for t in "${review_teams[@]}"; do
            if [[ "${t}" == "${ADD_REVIEW_TEAM}" ]]; then
                echo "Leaving \"$t\" as reviewer"
            else
                echo "Removing team \"$t\" as reviewer"
                gh api -X DELETE -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" "/repos/${GITHUB_REPOSITORY}/pulls/${PR_NUMBER}/requested_reviewers" -f "reviewers[]=" -f "team_reviewers[]=${t}" > /dev/null
            fi
        done

    - id: add-review-team
      name: Add review team
      if: ${{ !contains(steps.get.outputs.review_team_names, vars.ADD_REVIEW_TEAM) }}
      run: |
        echo "Adding team reviewer \"$ADD_REVIEW_TEAM\""
        gh api -X POST -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" "/repos/${GITHUB_REPOSITORY}/pulls/${PR_NUMBER}/requested_reviewers" -f "reviewers[]=" -f "team_reviewers[]=${ADD_REVIEW_TEAM}" #> /dev/null
